server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      global cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # Correct this URL if needed
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

# Uncomment and adjust routes as needed
#      routes:
#        - id: r1
#          uri: http://localhost:8082
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8084
#          predicates:
#            - Path=/products/**
